// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'Enter Value',
    appId: 'Enter Enter Value,
    messagingSenderId: 'Enter Value',
    projectId: 'Enter Value',
    authDomain: 'Enter Value',
    Enter Enter Value',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'Enter Value',
    appId: '1:332708430788:android:b6e7ca0ebbb7e91469da91',
    messagingSenderId: '332708430788',
    projectId: 'scape-nerf-fd54b',
    databaseURL: 'Enter Database URL',
    storageBucket: 'Enter Value',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'Enter Value',
    appId: '1:332708430788:ios:ca5ce1a2d2d6f1c169da91',
    messagingSenderId: '332708430788',
    projectId: 'scape-nerf-fd54b',
    databaseURL: 'Enter Database URL',
    storageBucket: 'Enter Value',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'Enter Value',
    appId: '1:332708430788:ios:ca5ce1a2d2d6f1c169da91',
    messagingSenderId: '332708430788',
    projectId: 'scape-nerf-fd54b',
    databaseURL: 'Enter Database URL',
    storageBucket: 'Enter Value',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'Enter Value',
    appId: '1:332708430788:web:6133a0bbb3f74efb69da91',
    messagingSenderId: '332708430788',
    projectId: 'scape-nerf-fd54b',
    authDomain: 'scape-nerf-fd54b.firebaseapp.com',
    databaseURL: 'Enter Database URL',
    storageBucket: 'Enter Value',
    measurementId: 'G-GQ6QEFJ5YN',
  );
}
